#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: Tarje
main: net.peacefulcraft.tarje.Tarje
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: [ Vault ]
softdepend: []

commands:
  tarjeadmin:
    description: Administration command for Tarje
  buy:
    aliases: [ shop ]
    description: Used to open the shop
    permission-message:  Sorry, you don't have access to open the shop
    usage: /<command> to open the shop
  sell:
    aliases: [ vender ]
    description: Used to open the sell menu
    permission-message:  Sorry, you don't have access to open the sell menu
    usage: /<command> to open the shop

permissions:
  tarje.*:
    description: Gives access to all tarje commands
    children:
      templateus.example: true
  tarje.buy:
    description: Access to open the shop
    default: true
  tarje.sell:
    description: Access to open the sell menu
    default: true
  tarje.admin:
    description: Access to Tarje administrative commands
    default: op
