package net.peacefulcraft.tarje.listeners;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;

import net.peacefulcraft.tarje.Tarje;
import net.peacefulcraft.tarje.shop.Shop;

public class InventoryClickListener implements Listener {

  @EventHandler
  public void onInventoryClick(InventoryClickEvent ev) {
    String inventoryName = ev.getView().getTitle();
    ItemStack clickedItem = ev.getCurrentItem();

    // Ignore if we clicked on a null item
    if (clickedItem == null) {
      return;
    }

    // Check if index shop
    if (inventoryName.equals("Server Shops")) {
      String clickedItemName = clickedItem.getItemMeta().getDisplayName();
      Shop requstedShop = Tarje._this().getShop(clickedItemName);
      ev.setCancelled(true);
      if (requstedShop == null) {
        Tarje._this().logSevere("Index shop is out of sync with registered shops! User requested shop " + clickedItemName + " from index, but that shop is either not enabled or not configured.");
        ((Player) ev.getView().getPlayer()).sendMessage(Tarje.messagingPrefix + "Sorry, this shop is misconfigured and can not be opened.");
      } else {
        ev.getView().close();
        requstedShop.openShop((Player) ev.getView().getPlayer());
      }


    // Check if clicked inventory was a shop
    } else if (Tarje._this().shopExists(inventoryName)) {
      Tarje._this().getShop(inventoryName).onShopInventoryClick((Player) ev.getView().getPlayer(), ev.getRawSlot(), ev.getCurrentItem());
      ev.setCancelled(true);


      // Check if clicked inventory was a purchase quantity inventory menu generated by a shop
    } else if (inventoryName.substring(0, 8).equals("Purchase")) {
      String shopName = inventoryName.split(" ")[1];
      ev.setCancelled(true);
      if (Tarje._this().shopExists(shopName)) {
        Tarje._this().getShop(shopName).onPurchaseQuantityInventoryClick((Player) ev.getView().getPlayer(), inventoryName, ev.getCurrentItem());
      } else {
        Tarje._this().logSevere("User attempted to purchase item from " + shopName + ", but no such shop could be found in configuration. This is likley caused by invalid characters in the shop name.");
        ((Player) ev.getView().getPlayer()).sendMessage(Tarje.messagingPrefix + "Sorry, this shop is misconfigured and can not be purchased from.");
      }
    }
  }
}