package net.peacefulcraft.tarje.listeners;

import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.inventory.ItemStack;

import net.peacefulcraft.tarje.Tarje;
import net.peacefulcraft.tarje.shop.ShopMenu;

public class InventoryClickListener implements Listener {

  @EventHandler(ignoreCancelled = true)
  public void onInventoryClick(InventoryClickEvent ev) {
    String inventoryName = ev.getView().getTitle();
    ItemStack clickedItem = ev.getCurrentItem();

    Tarje._this().logDebug("click on inventory " + inventoryName);

    // Check if index shop
    if (inventoryName.equals("Server Shops") && clickedItem != null) {
      String clickedItemName = clickedItem.getItemMeta().getDisplayName();
      ShopMenu requstedShop = Tarje._this().getShop(clickedItemName);
      ev.setCancelled(true);
      if (requstedShop == null) {
        Tarje._this().logSevere("Index shop is out of sync with registered shops! User requested shop " + clickedItemName + " from index, but that shop is either not enabled or not configured.");
        ((Player) ev.getView().getPlayer()).sendMessage(Tarje.messagingPrefix + "Sorry, this shop is misconfigured and can not be opened.");
      } else {
        ev.getView().close();
        requstedShop.openShop((Player) ev.getView().getPlayer());
      }


    // Check if clicked inventory was a shop
    } else if (Tarje._this().shopExists(inventoryName) && clickedItem != null) {
      Tarje._this().getShop(inventoryName).onShopInventoryClick((Player) ev.getView().getPlayer(), ev.getRawSlot(), ev.getCurrentItem());
      ev.setCancelled(true);


    // Check if clicked inventory was a purchase quantity inventory menu generated by a shop
    } else if (inventoryName.length() > 7 && inventoryName.substring(0, 8).equals("Purchase") && clickedItem != null) {

      String shopName = inventoryName.split(" ")[1];
      if (clickedItem.getType() == Material.BARRIER && clickedItem.getItemMeta().getDisplayName().equals("Cancel")) {
        ev.setCancelled(true);
        Tarje._this().synchronize(() -> {
          ev.getView().close();
          Tarje._this().getShop(shopName).openShop((Player) ev.getView().getPlayer());
        });
        return;
      }

      ev.setCancelled(true);
      Tarje._this().getShop(shopName).onPurchaseQuantityInventoryClick((Player) ev.getView().getPlayer(), inventoryName, ev.getCurrentItem());

    // Check if clicked inventory was a sell menu
    } else if (inventoryName.equals("Sell Items")) {
      Tarje._this().getSellMenu().onInventoryClick(ev);
    }
  }
}