package net.peacefulcraft.tarje.listeners;

import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;

import net.peacefulcraft.tarje.Tarje;

public class InventoryClickListener implements Listener {

  @EventHandler
  public void onInventoryClick(InventoryClickEvent ev) {
    String inventoryName = ev.getView().getTitle();

    // Check if clicked inventory was a shop
    if (Tarje._this().shopExists(inventoryName)) {
      Tarje._this().getShop(inventoryName).onShopInventoryClick((Player) ev.getView().getPlayer(), ev.getRawSlot(), ev.getCurrentItem());
      ev.setCancelled(true);
      return;
    }

    // Check if clicked inventory was a purchase quantity inventory menu generated by a shop
    if (inventoryName.substring(0, 7).equals("Purchase")) {
      String shopName = inventoryName.split(" ")[1];
      if (Tarje._this().shopExists(shopName)) {
        Tarje._this().getShop(shopName).onPurchaseQuantityInventoryClick((Player) ev.getView().getPlayer(), inventoryName, ev.getCurrentItem());
        return;
      }
    }
  }
}